# Do not edit. Generated by the configure script.
{
  "variables": {
    "without_ssl": "true", 
    "target_arch": "ia32", 
    "host_arch": "ia32", 
  }, 
  "target_defaults": {
    "libraries": [], 
    "defines": [], 
    "cflags": [], 
    "include_dirs": []
  }
}
